// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CarouselDocumentDataSlicesSlice = LogoCarouselSlice;

/**
 * Content for Carousel documents
 */
interface CarouselDocumentData {
  /**
   * Slice Zone field in *Carousel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CarouselDocumentDataSlicesSlice>;
}

/**
 * Carousel document from Prismic
 *
 * - **API ID**: `carousel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarouselDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CarouselDocumentData>,
    "carousel",
    Lang
  >;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Category field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type CategoryPageDocumentDataSlicesSlice =
  | CertificatesSlice
  | CarouselSlice
  | OurSolutionsSlice
  | TestimonialsSlice
  | YoutubeVideoSlice
  | PageOverviewSlice
  | ServiceCardsSlice
  | TechShowcaseSlice
  | ProductShowcaseSlice
  | ShowcaseSlice
  | TextSlice
  | BreadcrumbSlice
  | HeroSlice;

/**
 * Content for Category Page documents
 */
interface CategoryPageDocumentData {
  /**
   * Category field in *Category Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: category_page.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Slice Zone field in *Category Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: category_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoryPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Category Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: category_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Category Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Category Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: category_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Category Page document from Prismic
 *
 * - **API ID**: `category_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryPageDocumentData>,
    "category_page",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | LogoCarouselSlice
  | CarouselSlice
  | CertificatesSlice
  | ProductShowcaseSlice
  | ShowcaseSlice
  | TestimonialsSlice
  | AddressSlice
  | ServiceCardsSlice
  | TextContentSlice
  | HeroSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Layout → Logo*
 */
export interface LayoutDocumentDataLogoItem {
  /**
   * Logo Icon field in *Layout → Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo[].logo_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_icon: prismic.ImageField<never>;

  /**
   * Logo icon link field in *Layout → Logo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo[].logo_icon_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_icon_link: prismic.LinkField;
}

type LayoutDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Item in *Layout → Copy Right*
 */
export interface LayoutDocumentDataCopyRightItem {
  /**
   * Primary text field in *Layout → Copy Right*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copy_right[].primary_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_text: prismic.KeyTextField;

  /**
   * Secondary text field in *Layout → Copy Right*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copy_right[].secondary_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_text: prismic.KeyTextField;
}

type LayoutDocumentDataSlices1Slice = FooterItemSlice;

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Logo field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo[]
   * - **Tab**: header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logo: prismic.GroupField<Simplify<LayoutDocumentDataLogoItem>>;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice> /**
   * CTA logo link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_logo_link
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  cta_logo_link: prismic.LinkField;

  /**
   * CTA Link logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_link_logo
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_link_logo: prismic.ImageField<never>;

  /**
   * Address field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.address
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Phone number field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.phone_number
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Email field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.email
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Social Media field in *Layout*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_media
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media: prismic.ContentRelationshipField<"social_media">;

  /**
   * Copy Right field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copy_right[]
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  copy_right: prismic.GroupField<Simplify<LayoutDocumentDataCopyRightItem>>;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices1[]
   * - **Tab**: footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<LayoutDocumentDataSlices1Slice>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CarouselSlice
  | ServiceCardsSlice
  | TextSlice
  | TechShowcaseSlice
  | BreadcrumbSlice
  | ProductShowcaseSlice
  | ShowcaseSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SocialMediaDocumentDataSlicesSlice = SocialMediaSlice;

/**
 * Content for Social Media documents
 */
interface SocialMediaDocumentData {
  /**
   * Slice Zone field in *Social Media*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SocialMediaDocumentDataSlicesSlice>;
}

/**
 * Social Media document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaDocumentData>,
    "social_media",
    Lang
  >;

type SubMenuDocumentDataSlicesSlice = SubMenuItemSlice | HeadingSlice;

type SubMenuDocumentDataSlices1Slice = HeadingSlice | SubMenuItemSlice;

type SubMenuDocumentDataSlices2Slice = HeadingSlice | SubMenuItemSlice;

type SubMenuDocumentDataSlices3Slice = HeadingSlice | SubMenuItemSlice;

/**
 * Content for Sub menu documents
 */
interface SubMenuDocumentData {
  /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuDocumentDataSlicesSlice> /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<SubMenuDocumentDataSlices1Slice> /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<SubMenuDocumentDataSlices2Slice> /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices3[]
   * - **Tab**: Column 4
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<SubMenuDocumentDataSlices3Slice>;
}

/**
 * Sub menu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubMenuDocumentData>,
    "sub_menu",
    Lang
  >;

export type AllDocumentTypes =
  | CarouselDocument
  | CategoryDocument
  | CategoryPageDocument
  | HomePageDocument
  | LayoutDocument
  | PageDocument
  | SocialMediaDocument
  | SubMenuDocument;

/**
 * Primary content in *Address → Primary*
 */
export interface AddressSliceDefaultPrimary {
  /**
   * Padding top field in *Address → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: address.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Address → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: address.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *Address → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: address.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Image field in *Address → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: address.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Address → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Address → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Button field in *Address → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button: prismic.KeyTextField;
}

/**
 * Default variation for Address Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AddressSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Address*
 */
type AddressSliceVariation = AddressSliceDefault;

/**
 * Address Shared Slice
 *
 * - **API ID**: `address`
 * - **Description**: Address
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressSlice = prismic.SharedSlice<
  "address",
  AddressSliceVariation
>;

/**
 * Primary content in *Breadcrumb → Primary*
 */
export interface BreadcrumbSliceDefaultPrimary {
  /**
   * Padding top field in *Breadcrumb → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: breadcrumb.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Breadcrumb → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: breadcrumb.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *Breadcrumb → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: breadcrumb.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * CTA Link field in *Breadcrumb → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: breadcrumb.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Label field in *Breadcrumb → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: breadcrumb.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Primary content in *Breadcrumb → Items*
 */
export interface BreadcrumbSliceDefaultItem {
  /**
   * CTA Link field in *Breadcrumb → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: breadcrumb.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Label field in *Breadcrumb → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: breadcrumb.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for Breadcrumb Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BreadcrumbSliceDefaultPrimary>,
  Simplify<BreadcrumbSliceDefaultItem>
>;

/**
 * Slice variation for *Breadcrumb*
 */
type BreadcrumbSliceVariation = BreadcrumbSliceDefault;

/**
 * Breadcrumb Shared Slice
 *
 * - **API ID**: `breadcrumb`
 * - **Description**: Breadcrumb
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbSlice = prismic.SharedSlice<
  "breadcrumb",
  BreadcrumbSliceVariation
>;

/**
 * Primary content in *Carousel → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Padding top field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: carousel.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: carousel.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Carousel field in *Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.carousel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carousel: prismic.ContentRelationshipField<"carousel">;

  /**
   * Title field in *Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Certificates → Primary*
 */
export interface CertificatesSliceDefaultPrimary {
  /**
   * Background field in *Certificates → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: certificates.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *Certificates → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: certificates.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Certificates → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: certificates.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *Certificates → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certificates.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Certificates → Items*
 */
export interface CertificatesSliceDefaultItem {
  /**
   * Image field in *Certificates → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certificates.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Certificates Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertificatesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificatesSliceDefaultPrimary>,
  Simplify<CertificatesSliceDefaultItem>
>;

/**
 * Slice variation for *Certificates*
 */
type CertificatesSliceVariation = CertificatesSliceDefault;

/**
 * Certificates Shared Slice
 *
 * - **API ID**: `certificates`
 * - **Description**: Certificates
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertificatesSlice = prismic.SharedSlice<
  "certificates",
  CertificatesSliceVariation
>;

/**
 * Primary content in *FooterItem → Primary*
 */
export interface FooterItemSliceDefaultPrimary {
  /**
   * Title field in *FooterItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *FooterItem → Items*
 */
export interface FooterItemSliceDefaultItem {
  /**
   * CTA Label field in *FooterItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *FooterItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for FooterItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterItemSliceDefaultPrimary>,
  Simplify<FooterItemSliceDefaultItem>
>;

/**
 * Slice variation for *FooterItem*
 */
type FooterItemSliceVariation = FooterItemSliceDefault;

/**
 * FooterItem Shared Slice
 *
 * - **API ID**: `footer_item`
 * - **Description**: FooterItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSlice = prismic.SharedSlice<
  "footer_item",
  FooterItemSliceVariation
>;

/**
 * Primary content in *Heading → Primary*
 */
export interface HeadingSliceDefaultPrimary {
  /**
   * CTA Link field in *Heading → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: heading.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Label field in *Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for Heading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Heading*
 */
type HeadingSliceVariation = HeadingSliceDefault;

/**
 * Heading Shared Slice
 *
 * - **API ID**: `heading`
 * - **Description**: Heading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSlice = prismic.SharedSlice<
  "heading",
  HeadingSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Primary Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * Primary Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;

  /**
   * Secondary Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceSecondaryPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;
}

/**
 * Secondary variation for Hero Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<HeroSliceSecondaryPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceTertiaryPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Primary Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * Primary Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;

  /**
   * Secondary Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Tertiary variation for Hero Slice
 *
 * - **API ID**: `tertiary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceTertiary = prismic.SharedSliceVariation<
  "tertiary",
  Simplify<HeroSliceTertiaryPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceSecondary
  | HeroSliceTertiary;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LogoCarousel → Items*
 */
export interface LogoCarouselSliceDefaultItem {
  /**
   * Logo field in *LogoCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for LogoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<LogoCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *LogoCarousel*
 */
type LogoCarouselSliceVariation = LogoCarouselSliceDefault;

/**
 * LogoCarousel Shared Slice
 *
 * - **API ID**: `logo_carousel`
 * - **Description**: LogoCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoCarouselSlice = prismic.SharedSlice<
  "logo_carousel",
  LogoCarouselSliceVariation
>;

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceWithSubMenuPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Sub menu field in *MenuItem → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.sub_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu: prismic.ContentRelationshipField<"sub_menu">;
}

/**
 * With sub menu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  "withSubMenu",
  Simplify<MenuItemSliceWithSubMenuPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *OurSolutions → Primary*
 */
export interface OurSolutionsSliceDefaultPrimary {
  /**
   * Title field in *OurSolutions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Padding top field in *OurSolutions → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: our_solutions.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *OurSolutions → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: our_solutions.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *OurSolutions → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: our_solutions.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Image field in *OurSolutions → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for OurSolutions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurSolutionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurSolutionsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *OurSolutions → Primary*
 */
export interface OurSolutionsSliceWithDescriptionAndGridPrimary {
  /**
   * Padding top field in *OurSolutions → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: our_solutions.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *OurSolutions → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: our_solutions.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *OurSolutions → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: our_solutions.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Title field in *OurSolutions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *OurSolutions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Text Right Panel field in *OurSolutions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.text_right_panel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_right_panel: prismic.RichTextField;

  /**
   * Image field in *OurSolutions → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_solutions.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * withDescriptionAndGrid variation for OurSolutions Slice
 *
 * - **API ID**: `withDescriptionAndGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurSolutionsSliceWithDescriptionAndGrid =
  prismic.SharedSliceVariation<
    "withDescriptionAndGrid",
    Simplify<OurSolutionsSliceWithDescriptionAndGridPrimary>,
    never
  >;

/**
 * Slice variation for *OurSolutions*
 */
type OurSolutionsSliceVariation =
  | OurSolutionsSliceDefault
  | OurSolutionsSliceWithDescriptionAndGrid;

/**
 * OurSolutions Shared Slice
 *
 * - **API ID**: `our_solutions`
 * - **Description**: OurSolutions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurSolutionsSlice = prismic.SharedSlice<
  "our_solutions",
  OurSolutionsSliceVariation
>;

/**
 * Primary content in *PageOverview → Primary*
 */
export interface PageOverviewSliceDefaultPrimary {
  /**
   * Background field in *PageOverview → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.background
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  background: prismic.NumberField;

  /**
   * Padding top field in *PageOverview → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *PageOverview → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Category field in *PageOverview → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Title field in *PageOverview → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Icon field in *PageOverview → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *PageOverview → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_overview.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PageOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageOverview*
 */
type PageOverviewSliceVariation = PageOverviewSliceDefault;

/**
 * PageOverview Shared Slice
 *
 * - **API ID**: `page_overview`
 * - **Description**: PageOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageOverviewSlice = prismic.SharedSlice<
  "page_overview",
  PageOverviewSliceVariation
>;

/**
 * Primary content in *ProductShowcase → Primary*
 */
export interface ProductShowcaseSliceDefaultPrimary {
  /**
   * Background field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_showcase.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ProductShowcase → Items*
 */
export interface ProductShowcaseSliceDefaultItem {
  /**
   * Imge field in *ProductShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].imge
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imge: prismic.ImageField<never>;

  /**
   * Name field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Link field in *ProductShowcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Label field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductShowcaseSliceDefaultPrimary>,
  Simplify<ProductShowcaseSliceDefaultItem>
>;

/**
 * Primary content in *ProductShowcase → Primary*
 */
export interface ProductShowcaseSliceFlattenPrimary {
  /**
   * Background field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product_showcase.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ProductShowcase → Items*
 */
export interface ProductShowcaseSliceFlattenItem {
  /**
   * Imge field in *ProductShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].imge
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imge: prismic.ImageField<never>;

  /**
   * Name field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Link field in *ProductShowcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Label field in *ProductShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Flatten variation for ProductShowcase Slice
 *
 * - **API ID**: `flatten`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSliceFlatten = prismic.SharedSliceVariation<
  "flatten",
  Simplify<ProductShowcaseSliceFlattenPrimary>,
  Simplify<ProductShowcaseSliceFlattenItem>
>;

/**
 * Slice variation for *ProductShowcase*
 */
type ProductShowcaseSliceVariation =
  | ProductShowcaseSliceDefault
  | ProductShowcaseSliceFlatten;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `product_showcase`
 * - **Description**: ProductShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSlice = prismic.SharedSlice<
  "product_showcase",
  ProductShowcaseSliceVariation
>;

/**
 * Primary content in *ServiceCards → Primary*
 */
export interface ServiceCardsSliceDefaultPrimary {
  /**
   * Background field in *ServiceCards → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service_cards.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding bottom field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: service_cards.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Padding top field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: service_cards.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Title field in *ServiceCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ServiceCards → Items*
 */
export interface ServiceCardsSliceDefaultItem {
  /**
   * Link field in *ServiceCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *ServiceCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for ServiceCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceCardsSliceDefaultPrimary>,
  Simplify<ServiceCardsSliceDefaultItem>
>;

/**
 * Primary content in *ServiceCards → Primary*
 */
export interface ServiceCardsSliceGridWithoutIconPrimary {
  /**
   * Background field in *ServiceCards → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service_cards.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: service_cards.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: service_cards.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *ServiceCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ServiceCards → Items*
 */
export interface ServiceCardsSliceGridWithoutIconItem {
  /**
   * Title field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Grid without icon variation for ServiceCards Slice
 *
 * - **API ID**: `gridWithoutIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCardsSliceGridWithoutIcon = prismic.SharedSliceVariation<
  "gridWithoutIcon",
  Simplify<ServiceCardsSliceGridWithoutIconPrimary>,
  Simplify<ServiceCardsSliceGridWithoutIconItem>
>;

/**
 * Primary content in *ServiceCards → Primary*
 */
export interface ServiceCardsSliceGridCardBasicPrimary {
  /**
   * Title field in *ServiceCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Padding top field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: service_cards.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *ServiceCards → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: service_cards.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *ServiceCards → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service_cards.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;
}

/**
 * Primary content in *ServiceCards → Items*
 */
export interface ServiceCardsSliceGridCardBasicItem {
  /**
   * Title field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Description Secondary field in *ServiceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].description_secondary
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_secondary: prismic.KeyTextField;

  /**
   * Link field in *ServiceCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_cards.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Grid Card Basic variation for ServiceCards Slice
 *
 * - **API ID**: `gridCardBasic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCardsSliceGridCardBasic = prismic.SharedSliceVariation<
  "gridCardBasic",
  Simplify<ServiceCardsSliceGridCardBasicPrimary>,
  Simplify<ServiceCardsSliceGridCardBasicItem>
>;

/**
 * Slice variation for *ServiceCards*
 */
type ServiceCardsSliceVariation =
  | ServiceCardsSliceDefault
  | ServiceCardsSliceGridWithoutIcon
  | ServiceCardsSliceGridCardBasic;

/**
 * ServiceCards Shared Slice
 *
 * - **API ID**: `service_cards`
 * - **Description**: ServiceCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCardsSlice = prismic.SharedSlice<
  "service_cards",
  ServiceCardsSliceVariation
>;

/**
 * Primary content in *Showcase → Primary*
 */
export interface ShowcaseSliceDefaultPrimary {
  /**
   * Title field in *Showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Label field in *Showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Showcase → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Image field in *Showcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Info image field in *Showcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.info_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  info_image: prismic.ImageField<never>;
}

/**
 * Default variation for Showcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Showcase → Primary*
 */
export interface ShowcaseSliceWithCategoryPrimary {
  /**
   * Title field in *Showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Label field in *Showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Showcase → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Image field in *Showcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Info image field in *Showcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.info_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  info_image: prismic.ImageField<never>;

  /**
   * Category field in *Showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;
}

/**
 * With Category variation for Showcase Slice
 *
 * - **API ID**: `withCategory`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSliceWithCategory = prismic.SharedSliceVariation<
  "withCategory",
  Simplify<ShowcaseSliceWithCategoryPrimary>,
  never
>;

/**
 * Slice variation for *Showcase*
 */
type ShowcaseSliceVariation = ShowcaseSliceDefault | ShowcaseSliceWithCategory;

/**
 * Showcase Shared Slice
 *
 * - **API ID**: `showcase`
 * - **Description**: Showcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSlice = prismic.SharedSlice<
  "showcase",
  ShowcaseSliceVariation
>;

/**
 * Primary content in *SocialMedia → Items*
 */
export interface SocialMediaSliceDefaultItem {
  /**
   * CTA Link field in *SocialMedia → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Icon field in *SocialMedia → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for SocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialMediaSliceDefaultItem>
>;

/**
 * Slice variation for *SocialMedia*
 */
type SocialMediaSliceVariation = SocialMediaSliceDefault;

/**
 * SocialMedia Shared Slice
 *
 * - **API ID**: `social_media`
 * - **Description**: SocialMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSlice = prismic.SharedSlice<
  "social_media",
  SocialMediaSliceVariation
>;

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceDefaultPrimary {
  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: label
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for SubMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubMenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceButtonPrimary {
  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Button variation for SubMenuItem Slice
 *
 * - **API ID**: `button`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceButton = prismic.SharedSliceVariation<
  "button",
  Simplify<SubMenuItemSliceButtonPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceBoxPrimary {
  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Description field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Box variation for SubMenuItem Slice
 *
 * - **API ID**: `box`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceBox = prismic.SharedSliceVariation<
  "box",
  Simplify<SubMenuItemSliceBoxPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceWithIconPrimary {
  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icon field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * withIcon variation for SubMenuItem Slice
 *
 * - **API ID**: `withIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceWithIcon = prismic.SharedSliceVariation<
  "withIcon",
  Simplify<SubMenuItemSliceWithIconPrimary>,
  never
>;

/**
 * Slice variation for *SubMenuItem*
 */
type SubMenuItemSliceVariation =
  | SubMenuItemSliceDefault
  | SubMenuItemSliceButton
  | SubMenuItemSliceBox
  | SubMenuItemSliceWithIcon;

/**
 * SubMenuItem Shared Slice
 *
 * - **API ID**: `sub_menu_item`
 * - **Description**: SubMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSlice = prismic.SharedSlice<
  "sub_menu_item",
  SubMenuItemSliceVariation
>;

/**
 * Primary content in *TechShowcase → Primary*
 */
export interface TechShowcaseSliceDefaultPrimary {
  /**
   * Background field in *TechShowcase → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tech_showcase.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *TechShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *TechShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *TechShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *TechShowcase → Items*
 */
export interface TechShowcaseSliceDefaultItem {
  /**
   * Image field in *TechShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TechShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechShowcaseSliceDefaultPrimary>,
  Simplify<TechShowcaseSliceDefaultItem>
>;

/**
 * Primary content in *TechShowcase → Primary*
 */
export interface TechShowcaseSliceWithTitlePrimary {
  /**
   * Background field in *TechShowcase → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tech_showcase.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *TechShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *TechShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *TechShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *TechShowcase → Items*
 */
export interface TechShowcaseSliceWithTitleItem {
  /**
   * Image field in *TechShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_showcase.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With title variation for TechShowcase Slice
 *
 * - **API ID**: `withTitle`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechShowcaseSliceWithTitle = prismic.SharedSliceVariation<
  "withTitle",
  Simplify<TechShowcaseSliceWithTitlePrimary>,
  Simplify<TechShowcaseSliceWithTitleItem>
>;

/**
 * Slice variation for *TechShowcase*
 */
type TechShowcaseSliceVariation =
  | TechShowcaseSliceDefault
  | TechShowcaseSliceWithTitle;

/**
 * TechShowcase Shared Slice
 *
 * - **API ID**: `tech_showcase`
 * - **Description**: TechShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechShowcaseSlice = prismic.SharedSlice<
  "tech_showcase",
  TechShowcaseSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Background field in *Testimonials → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonials.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *Testimonials → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Testimonials → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Name field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Job title field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.job_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.RichTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceWithSlicePrimary {
  /**
   * Background field in *Testimonials → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonials.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *Testimonials → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Testimonials → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceWithSliceItem {
  /**
   * Description field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Name field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Job title field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].job_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.RichTextField;
}

/**
 * withSlice variation for Testimonials Slice
 *
 * - **API ID**: `withSlice`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceWithSlice = prismic.SharedSliceVariation<
  "withSlice",
  Simplify<TestimonialsSliceWithSlicePrimary>,
  Simplify<TestimonialsSliceWithSliceItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation =
  | TestimonialsSliceDefault
  | TestimonialsSliceWithSlice;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Padding top field in *Text → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: text.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Text → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: text.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Tag field in *Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceWithBackgroundColorPrimary {
  /**
   * Padding top field in *Text → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *Text → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Background field in *Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Tag field in *Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * With Background Color variation for Text Slice
 *
 * - **API ID**: `withBackgroundColor`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceWithBackgroundColor = prismic.SharedSliceVariation<
  "withBackgroundColor",
  Simplify<TextSliceWithBackgroundColorPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceWithBackgroundColor;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextContent → Primary*
 */
export interface TextContentSliceDefaultPrimary {
  /**
   * Padding top field in *TextContent → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: text_content.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *TextContent → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: text_content.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Title field in *TextContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub title field in *TextContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;
}

/**
 * Primary content in *TextContent → Items*
 */
export interface TextContentSliceDefaultItem {
  /**
   * Description main field in *TextContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.items[].description_main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_main: prismic.KeyTextField;

  /**
   * Description sub field in *TextContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.items[].description_sub
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_sub: prismic.KeyTextField;
}

/**
 * Default variation for TextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextContentSliceDefaultPrimary>,
  Simplify<TextContentSliceDefaultItem>
>;

/**
 * Slice variation for *TextContent*
 */
type TextContentSliceVariation = TextContentSliceDefault;

/**
 * TextContent Shared Slice
 *
 * - **API ID**: `text_content`
 * - **Description**: TextContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSlice = prismic.SharedSlice<
  "text_content",
  TextContentSliceVariation
>;

/**
 * Primary content in *YoutubeVideo → Primary*
 */
export interface YoutubeVideoSliceDefaultPrimary {
  /**
   * Background field in *YoutubeVideo → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: youtube_video.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Padding top field in *YoutubeVideo → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding top (Ex: 10 => padding-top: 10px)
   * - **API ID Path**: youtube_video.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_top: prismic.NumberField;

  /**
   * Padding bottom field in *YoutubeVideo → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Custom padding bottom (Ex: 10 => padding-bottom: 10px)
   * - **API ID Path**: youtube_video.primary.padding_bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_bottom: prismic.NumberField;

  /**
   * Video ID field in *YoutubeVideo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_video.primary.video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_id: prismic.KeyTextField;
}

/**
 * Default variation for YoutubeVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YoutubeVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *YoutubeVideo*
 */
type YoutubeVideoSliceVariation = YoutubeVideoSliceDefault;

/**
 * YoutubeVideo Shared Slice
 *
 * - **API ID**: `youtube_video`
 * - **Description**: YoutubeVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeVideoSlice = prismic.SharedSlice<
  "youtube_video",
  YoutubeVideoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CarouselDocument,
      CarouselDocumentData,
      CarouselDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      CategoryPageDocument,
      CategoryPageDocumentData,
      CategoryPageDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataLogoItem,
      LayoutDocumentDataSlicesSlice,
      LayoutDocumentDataCopyRightItem,
      LayoutDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SocialMediaDocument,
      SocialMediaDocumentData,
      SocialMediaDocumentDataSlicesSlice,
      SubMenuDocument,
      SubMenuDocumentData,
      SubMenuDocumentDataSlicesSlice,
      SubMenuDocumentDataSlices1Slice,
      SubMenuDocumentDataSlices2Slice,
      SubMenuDocumentDataSlices3Slice,
      AllDocumentTypes,
      AddressSlice,
      AddressSliceDefaultPrimary,
      AddressSliceVariation,
      AddressSliceDefault,
      BreadcrumbSlice,
      BreadcrumbSliceDefaultPrimary,
      BreadcrumbSliceDefaultItem,
      BreadcrumbSliceVariation,
      BreadcrumbSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      CertificatesSlice,
      CertificatesSliceDefaultPrimary,
      CertificatesSliceDefaultItem,
      CertificatesSliceVariation,
      CertificatesSliceDefault,
      FooterItemSlice,
      FooterItemSliceDefaultPrimary,
      FooterItemSliceDefaultItem,
      FooterItemSliceVariation,
      FooterItemSliceDefault,
      HeadingSlice,
      HeadingSliceDefaultPrimary,
      HeadingSliceVariation,
      HeadingSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSecondaryPrimary,
      HeroSliceTertiaryPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSecondary,
      HeroSliceTertiary,
      LogoCarouselSlice,
      LogoCarouselSliceDefaultItem,
      LogoCarouselSliceVariation,
      LogoCarouselSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceWithSubMenuPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      OurSolutionsSlice,
      OurSolutionsSliceDefaultPrimary,
      OurSolutionsSliceWithDescriptionAndGridPrimary,
      OurSolutionsSliceVariation,
      OurSolutionsSliceDefault,
      OurSolutionsSliceWithDescriptionAndGrid,
      PageOverviewSlice,
      PageOverviewSliceDefaultPrimary,
      PageOverviewSliceVariation,
      PageOverviewSliceDefault,
      ProductShowcaseSlice,
      ProductShowcaseSliceDefaultPrimary,
      ProductShowcaseSliceDefaultItem,
      ProductShowcaseSliceFlattenPrimary,
      ProductShowcaseSliceFlattenItem,
      ProductShowcaseSliceVariation,
      ProductShowcaseSliceDefault,
      ProductShowcaseSliceFlatten,
      ServiceCardsSlice,
      ServiceCardsSliceDefaultPrimary,
      ServiceCardsSliceDefaultItem,
      ServiceCardsSliceGridWithoutIconPrimary,
      ServiceCardsSliceGridWithoutIconItem,
      ServiceCardsSliceGridCardBasicPrimary,
      ServiceCardsSliceGridCardBasicItem,
      ServiceCardsSliceVariation,
      ServiceCardsSliceDefault,
      ServiceCardsSliceGridWithoutIcon,
      ServiceCardsSliceGridCardBasic,
      ShowcaseSlice,
      ShowcaseSliceDefaultPrimary,
      ShowcaseSliceWithCategoryPrimary,
      ShowcaseSliceVariation,
      ShowcaseSliceDefault,
      ShowcaseSliceWithCategory,
      SocialMediaSlice,
      SocialMediaSliceDefaultItem,
      SocialMediaSliceVariation,
      SocialMediaSliceDefault,
      SubMenuItemSlice,
      SubMenuItemSliceDefaultPrimary,
      SubMenuItemSliceButtonPrimary,
      SubMenuItemSliceBoxPrimary,
      SubMenuItemSliceWithIconPrimary,
      SubMenuItemSliceVariation,
      SubMenuItemSliceDefault,
      SubMenuItemSliceButton,
      SubMenuItemSliceBox,
      SubMenuItemSliceWithIcon,
      TechShowcaseSlice,
      TechShowcaseSliceDefaultPrimary,
      TechShowcaseSliceDefaultItem,
      TechShowcaseSliceWithTitlePrimary,
      TechShowcaseSliceWithTitleItem,
      TechShowcaseSliceVariation,
      TechShowcaseSliceDefault,
      TechShowcaseSliceWithTitle,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceWithSlicePrimary,
      TestimonialsSliceWithSliceItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TestimonialsSliceWithSlice,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceWithBackgroundColorPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceWithBackgroundColor,
      TextContentSlice,
      TextContentSliceDefaultPrimary,
      TextContentSliceDefaultItem,
      TextContentSliceVariation,
      TextContentSliceDefault,
      YoutubeVideoSlice,
      YoutubeVideoSliceDefaultPrimary,
      YoutubeVideoSliceVariation,
      YoutubeVideoSliceDefault,
    };
  }
}
