// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  address: dynamic(() => import("./Address")),
  certificates: dynamic(() => import("./Certificates")),
  heading: dynamic(() => import("./Heading")),
  hero: dynamic(() => import("./Hero")),
  logo_carousel: dynamic(() => import("./LogoCarousel")),
  menu_item: dynamic(() => import("./MenuItem")),
  product_showcase: dynamic(() => import("./ProductShowcase")),
  service_cards: dynamic(() => import("./ServiceCards")),
  showcase: dynamic(() => import("./Showcase")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_content: dynamic(() => import("./TextContent")),
};
