// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  banner: dynamic(() => import('./Banner')),
  blog_content: dynamic(() => import('./BlogContent')),
  breadcrumb: dynamic(() => import('./Breadcrumb')),
  careers: dynamic(() => import('./Careers')),
  carousel: dynamic(() => import('./Carousel')),
  carousel_util: dynamic(() => import('./CarouselUtil')),
  case_study: dynamic(() => import('./CaseStudy')),
  certificate: dynamic(() => import('./Certificate')),
  contact_us_form: dynamic(() => import('./ContactUsForm')),
  development_approach: dynamic(() => import('./DevelopmentApproach')),
  footer_item: dynamic(() => import('./FooterItem')),
  grid_card: dynamic(() => import('./GridCard')),
  image_slice: dynamic(() => import('./ImageSlice')),
  industries_served: dynamic(() => import('./IndustriesServed')),
  innovation_lead: dynamic(() => import('./InnovationLead')),
  leader_detail: dynamic(() => import('./LeaderDetail')),
  menu_item: dynamic(() => import('./MenuItem')),
  our_vision: dynamic(() => import('./OurVision')),
  resources: dynamic(() => import('./Resources')),
  showcase: dynamic(() => import('./Showcase')),
  similar_case_studies: dynamic(() => import('./SimilarCaseStudies')),
  similar_post: dynamic(() => import('./SimilarPost')),
  single_heading: dynamic(() => import('./SingleHeading')),
  social_media: dynamic(() => import('./SocialMedia')),
  sub_menu_item: dynamic(() => import('./SubMenuItem')),
  submenu_header: dynamic(() => import('./SubmenuHeader')),
  talk_to_expert_form: dynamic(() => import('./TalkToExpertForm')),
  testimonials: dynamic(() => import('./Testimonials')),
  text_with_image: dynamic(() => import('./TextWithImage')),
  video_block: dynamic(() => import('./VideoBlock')),
  we_are_here: dynamic(() => import('./WeAreHere'))
}
