import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrismicNextLink, PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import '@/styles/globals.css'
import Link from "next/link";
import { PrismicText } from "@prismicio/react";
import Header from "@/components/Header/Header";

import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <section className="">
          {children}
        </section>
        <Footer />
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
