import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import '@/styles/globals.css'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["https://www.poetadigital.com/hubfs/favicon.png"]
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const client = createClient();
  const layout = await client.getSingle('layout')

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-dvh">
          <Header layout={layout}/>
          <section className="flex-grow">
            {children}
          </section>
          <Footer layout={layout}/>
        </div>
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
