import type { Metadata } from 'next'
import { PrismicPreview } from '@prismicio/next'
import { createClient, repositoryName } from '@/prismicio'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import StoreProvider from '@/components/layout/StoreProvider'

import { Source_Sans_3 } from 'next/font/google'

import '@fortawesome/fontawesome-svg-core/styles.css' // import Font Awesome CSS
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Poeta',
  description: 'Generated by create next app',
  icons: ['/images/favicon.png']
}

const sourceCodePro = Source_Sans_3({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-sourceCodePro'
})

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = createClient()
  const layout = await client.getSingle('layout')

  return (
    <html lang='en'>
      <body className={`${sourceCodePro.variable}`}>
        <div className='flex h-dvh flex-col'>
          <Header layout={layout} />
          <StoreProvider>
            <h1 className='sr-only'>SEO</h1>
            <h2 className='sr-only'>SEO</h2>
            <section className='flex-grow'>{children}</section>
          </StoreProvider>
          <Footer layout={layout} />
        </div>
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  )
}
